# The URL the site will be built for
base_url = "https://attajak.github.io/zola-demo/"

# The title of the site
title = "Zola Demo"

# The description of the site
description = "Hacker is a theme for Zola"

theme = "hacker"

author = "Attajak Janrak"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the HTML when building the site
minify_html = true

# Whether to generate an Atom feed
generate_feeds = true

# Taxonomies
taxonomies = [
  { name = "tags" }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "charcoal"

# Whether to render emojis
render_emoji = true

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = true

[extra]
title_separator = "|" # set as |, -, _, etc

# The path to the logo of the site
logo = "apple-touch-icon.png"

# Google Analytics tracking ID
# google_analytics = "example-tracking-id"

# Contact form script id that points to google macros (e.g. https://script.google.com/macros/s/<script-identifier>/exec)
# More info about contact form based on google macros can be found here: https://github.com/en9inerd/learn-to-send-email-via-google-script-html-no-server
contact_form_script_id = "<script-identifier>"

# Visitor notifier based on IFTTT + Webhooks. Sample here - /static/js/monitor.js
monitor = false

# Menu items
menu = [
  { url = "/", name = "Home" },
  { url = "/about", name = "About" },
  { url = "/tags", name = "Tags" }
]

language_code = "en-US"

# Enable OpenGraph metadata
opengraph = true

timezone = "Asia/Bangkok"
# timeformat = ""

# The path to cv file if you use cv shortcode
# cv_file = "/files/Curriculum_Vitae.pdf"

# provide link to edit page on github
edit_page = true

# Use theme specific tags page based on templates/tags.html
simplified_tags = false

# Social links
social_links = [
  { platform = "email", user_id = "janrak@gmail.com" },
  { platform = "github", user_id = "attajak" },
  { platform = "linkedin", user_id = "attajak" },
  { platform = "feed", user_id = true },
  # { platform = "keyoxide", user_id = "aspe:host:XXXXXXX" },
  { platform = "facebook", user_id = "attajak" },
  { platform = "instagram", user_id = "attajak" },
  # { platform = "pinterest", user_id = "" },
  { platform = "twitter", user_id = "attajak" },
  # { platform = "stackoverflow", user_id = "" },
  { platform = "youtube", user_id = "@attjak" },
  { platform = "telegram", user_id = "attajak" },
]

# GitHub settings that are used to generate the edit page link
[extra.github]
username = "attajak"
repo = "zola-demo"

# Giscus settings
[extra.giscus]
repo = "attajak/zola-demo"
repo_id = "" # "R_kgDOMZOW5g"
category = "Comments"
category_id = "" # "DIC_kwDOMZOW5s4ChFNw"
mapping = "og:title"
strict = 0
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "dark"
lang = "en"
loading = "lazy"
crossorigin = "anonymous"

# PGP key
[extra.pgp_key]
url = "https://keys.openpgp.org/vks/v1/by-fingerprint/0000000000000000000000000000000000000000"
fingerprint = "0000 0000 0000 0000 0000 0000 0000 0000 0000 0000"

# JSON-LD metadata
[extra.bio]
gender = "male"
employer_name = "Attajak Janrak"
employer_url = "https://attajak.github.io"
job_title = "Software Engineer"
links = [
  "https://github.com/attajak",
  "https://linkedin.com/in/attajak",
  "https://twitter.com/attajak",
]
